services:
  vblanding:
    build: .
    container_name: vblanding
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: CHANGE_ME_NPM_NETWORK_NAME
